[package]
name = "gbump"
version = "1.1.3"
authors = ["Nicolas Embriz <nbari@tequila.io>"]
description = "Git tag semantic version bumper"
documentation = "https://crates.io/crates/gbump"
homepage = "https://github.com/nbari/gbump"
repository = "https://github.com/nbari/gbump"
readme = "README.md"
keywords = ["git", "semver", "cli", "versioning", "release"]
categories = ["command-line-utilities", "development-tools::version-control"]
license = "BSD-3-Clause"
edition = "2024"

[features]
default = []
musl = ["openssl/vendored"]

[dependencies]
regex = "1.11"
clap = "4"
openssl = { version = "0.10", optional = true, features = ["vendored"] }
git2 = "0.20"
semver = "1.0"

[dev-dependencies]
tempfile = "3"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/gbump", dest = "/usr/bin/gbump", mode = "755" },
]

[package.metadata.deb]
assets = [
  ["target/release/gbump", "/usr/bin/cron-when", "755"],
]
depends = ""
